#Job de construction de l'image
build-images:
  stage: build
  image: docker:dind
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - ue25 # Tag obligatoire pour le runner
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}